### ISSUE TITLE
Just some passing ideas, feel free to ignore

### ISSUE THREAD

**Issue by airlied** [g-truc/glo#2]
I expect you really want to use Mesa if you want a full GL API. Mesa implements all of the error checking and the boring crappy stuff needed. You would then interface the Mesa device driver interface to the Vulkan API. The device driver interface happens after all the generic error checking and API unpacking.

The big problem I forsaw with this is how to integrate bindings, like EGL with the Vulkan WSI layer, I did wonder if a VGL would be a better plan and be able to create GL contexts on a vulkan display connection. So you wouldn't be able to use old apps but you could program GL and vulkan side by side a lot easier.

**Comment by Groovounet** [comment]
Hi,
Is there a clearly isolated OpenGL front-end in Mesa? It didn't appeared to me this is the case.

**Comment by airlied** [comment]
src/mapi/ for the GL API construction,
src/mesa/main for all the GL API implementation, dd.h is the main driver header file.

src/mesa/vbo has some useful helpers, then really the rest is ignorable.

Just look at how many loc are in src/mesa/main and realise to get GL you need to rewrite all of that, no matter where you start from that is a long hard slogfest. Angle is OpenGLES2.0, that is a pretty small API compared to the full desktop GL API. If you are just targeting GLES then you still have to deal with GLES3.0, 3.1, 3.2 which shares a lot of code with desktop GL.

**Comment by jrmuizel** [comment]
ANGLE has OpenGLES 3 now and the beginnings of an Vulkan backend with goal of fleshing it out in the near term.
