### ISSUE TITLE
Why a DX12 backend?

### ISSUE THREAD

**Issue by andrebrait** [g-truc/glo#3]
I am genuinely curious as to why there should be a DX12 backend. Every DX12 card has Vulkan drivers and DX12 is only compatible with Windows 10 whereas Vulkan is compatible with anything as long as the drivers support Vulkan. Are there cases where a platform would have working DX12 support but no Vulkan?

**Comment by Groovounet** [comment]
Because why not. This said: this is not for tomorrow anyway so it might never hppan. Currently I focus on Vulkan and then (already we reach #lol) I guess it will be Metal... Well.

**Comment by andrebrait** [comment]
I see. Thanks for answering the question!
