### ISSUE TITLE
GLO is incomplete?

### ISSUE THREAD

**Issue by acterhd** [g-truc/glo#4]
Hello. I looked source code, but seen that source code incomplete. 
I at same time working on wrapper for OpenGL, and would be good if will support for multi-context, multi-device, and etc. At this time I ported shaders of my path tracer for future versions of OpenGL. Also, I have adapted version of Conservative Rasterization (i.e. voxelizer) for Vulkan-like applications. 
Main question: when I can use GLO for my wrapper support? I'm not so good know Vulkan API, but I try workaround all modern OpenGL with high level wrappers...

**Comment by Groovounet** [comment]
Hi,

Yes it's totally not complete, nearly all the work remains to be done and will take years.

Thanks,
Christophe
